### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by nbilbeny** [vvr-rao/Chatbot-using-GPT35-turbo#1]
Hey, interesting project.

On running main35T.py I get:

```
black@MacBook-Pro Chatbot-using-GPT35-turbo %  cd /Users/black/gpt/Chatbot-using-GPT35-turbo ; /usr/bin/env /Users/black/.pyenv/shims/python /Users/black/.vscode/extensions/ms
-python.python-2023.4.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 52261 -- /Users/black/gpt/Chatbot-using-GPT35-turbo/code/main35T.py 
Human(enter q to quit):can you give me a historical overview of Historical overview of COP 2009-2017
unable to open database file
Traceback (most recent call last):
  File "/Users/black/gpt/Chatbot-using-GPT35-turbo/code/main35T.py", line 29, in <module>
    context = getContext(context_searcher) 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/black/gpt/Chatbot-using-GPT35-turbo/code/EmbeddingsHelper.py", line 62, in getContext
    best_match = int(res['matches'][0]['id'])
                     ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by troublesprouter** [comment]
It may be a problem with installing this dependency actually:

```
black@MacBook-Pro Chatbot-using-GPT35-turbo % pip3 install scipy         
Collecting scipy
  Using cached scipy-1.10.1.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      The Meson build system
      Version: 1.0.1
      Source dir: /private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-install-u5fn3x7v/scipy_cff727e466eb47b1bc51f72b0be037b7
      Build dir: /private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-install-u5fn3x7v/scipy_cff727e466eb47b1bc51f72b0be037b7/.mesonpy-p1ha5j0o/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.1
      C compiler for the host machine: cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C linker for the host machine: cc ld64 711
      C++ compiler for the host machine: c++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C++ linker for the host machine: c++ ld64 711
      Cython compiler for the host machine: cython (cython 0.29.33)
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 12.2.0 "GNU Fortran (Homebrew GCC 12.2.0) 12.2.0")
      Fortran linker for the host machine: gfortran ld64 711
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: NO
      Program cython found: YES (/private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-build-env-taoz8vzt/overlay/bin/cython)
      Program python found: YES (/Users/black/.pyenv/versions/3.11.2/bin/python3.11)
      Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
      Program pythran found: YES (/private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-build-env-taoz8vzt/overlay/bin/pythran)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      Found CMake: /opt/homebrew/bin/cmake (3.25.3)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      
      ../../scipy/meson.build:134:0: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig, framework and cmake
      
      A full log can be found at /private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-install-u5fn3x7v/scipy_cff727e466eb47b1bc51f72b0be037b7/.mesonpy-p1ha5j0o/build/meson-logs/meson-log.txt
      + meson setup --prefix=/Users/black/.pyenv/versions/3.11.2 /private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-install-u5fn3x7v/scipy_cff727e466eb47b1bc51f72b0be037b7 /private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-install-u5fn3x7v/scipy_cff727e466eb47b1bc51f72b0be037b7/.mesonpy-p1ha5j0o/build --native-file=/private/var/folders/dj/xlvh6h716039b311c_7w4lkr0000gn/T/pip-install-u5fn3x7v/scipy_cff727e466eb47b1bc51f72b0be037b7/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
